<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ChooseAction" Id="{6e6a5cf2-af70-4f86-924a-c262843e85ff}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ChooseAction
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ChooseAction">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>