<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_OdometryOpponents" Id="{b0c0ab87-41b9-4d27-8187-f433cf8bb0e9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_OdometryOpponents
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_OdometryOpponents">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>