<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="Test" Id="{05a7abdc-a21b-48aa-9907-14c130b4fdc8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Test
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>